### PR TITLE
add GraphQL query to query vfolder with id

### PR DESCRIPTION
**Pull request by fregataa**
migrate from https://github.com/lablup/backend.ai-manager/pull/597

~~blocked by #574~~

### CODE REVIEW

**Review by achimnol — CHANGES_REQUESTED** [review]
Please apply the dataloader to batch multiple vfolder queries.

**Review by achimnol — APPROVED** [review]

**Review by achimnol — CHANGES_REQUESTED** [review]
I think the current implementation looks nice.

Though, let's extend it to allow non-admin users to query about their own vfolders with IDs while limiting query other user's vfolders.
Could we use something like `ai.backend.manager.models.base.scoped_query()`?

Since we need a separate multi-query implementation `ai.backend.manager.models.vfolder.query_accessible_vfolders()`, it might not be possible to directly reuse `scoped_query()` as-is.  How about adding an ID-based version of `query_accessible_vfolders()`?  For instance, we could fetch vfolders based on the IDs with privilege check conditions.

**Comment by fregataa** [comment]
> Since we need a separate multi-query implementation `ai.backend.manager.models.vfolder.query_accessible_vfolders()`, it might not be possible to directly reuse `scoped_query()` as-is. How about adding an ID-based version of `query_accessible_vfolders()`? For instance, we could fetch vfolders based on the IDs with privilege check conditions.

privilege checking for vfolders is too complicated to simplify, I implemented ID-based version of `query_accessible_vfolders()` as very similar with `query_accessible_vfolders()`. Do I need to abstract privilege checking for RBAC?

**Comment by achimnol** [comment]
This should be updated to work with #1386.

**Review by achimnol — APPROVED** [review]

**Review by achimnol — COMMENTED** [review]
`scoped_query` will provide user-level ownership check.

But, we also need to check scenarios like:
- Querying project-owned vfolders by a normal user
- Querying either user-owned/project-owned vfolders by a superadmin

Ideally we need to have a separate `vfolder_ownership` relation table, but to narrow the scope of this PR, we could declare that "vfolder GraphQL API is only for user-owned vfolders for now" or "superadmin-only" as an alternative.

**Review by achimnol — APPROVED** [review]

**Pull request merged**
