### PR TITLE
feature: Auto-generate and auto-commit news fragment from PR title

### PR DESCRIPTION
**Pull request by soheeeeP**
issue #742 

#### Description
- Add the python script `scripts/update-news-fragment.py` to handle the news fragments.
  - Check existence of the news fragment from the matching labels 
  - Create the news fragment by first assigned label when it does not exist.
  - Updates the news fragment by using the changed PR title
- Update `timeline-check.yml` action workflow to generate auto-commit, auto-push the news fragments

#### Question
- I didn't find a clear approach to retrieve the content of the previous PR title, so updated the news fragment for all cases when the PR title changes.

### CODE REVIEW

**Comment by Yaminyam** [comment]
If the ci works normally, shouldn't the news fragment of the pr be created automatically?

**Comment by soheeeeP** [comment]
@Yaminyam I've designed the ci workflow to be activated when more than one label is assigned to the PR.

**Comment by Yaminyam** [comment]
I thought that the label we were talking about in this issue was not the PR label, but the (eg ci:) label in the PR title.
You might want to check out this part!

**Comment by soheeeeP** [comment]
I think PR from forked repository does not have permission to read the secrets of upstream repository. (like what happened in #687. Is there any possible ways to access secret?
image

**Comment by Yaminyam** [comment]
> @Yaminyam I think PR from forked repository does not have permission to read the secrets of upstream repository. (like what happened in #687. Is there any possible ways to access secret? image

I think it's probably not.
In the case of me, if a secret is needed, I made a repo for testing and confirmed that it works normally and submitted the pr.

**Comment by achimnol** [comment]
In favor of #989, I'd like to keep manual writing of news fragments because they can provide more details compared to PR titles.

**Pull request closed without merging**
