### PR TITLE
fix: change exit code from -1 to 1

### PR DESCRIPTION
**Pull request by jangjichang**
Change exit code.

issue: [580](https://github.com/lablup/backend.ai/issues/580)

### CODE REVIEW

**Review by kyujin-cho — COMMENTED** [review]
LGTM!

**Review by kyujin-cho — APPROVED** [review]

**Review by kyujin-cho — CHANGES_REQUESTED** [review]
Please add news fragment before merging.

**Comment by achimnol** [comment]
I think we don't need an explicit news fragment for this PR, as this wouldn't have noticeable impacts on the users.

**Comment by achimnol** [comment]
Another issue for this PR:
image

As I said, please make a new branch after forking!!!

**Comment by achimnol** [comment]
> As I said, please make a new branch after forking!!!
> 
> Since now we have explicit lint/check runs for all commits and pushes as git hooks, this would make other people to get mad.

Hmmmm, this PR already has a new branch in the fork. I'm looking into more.

**Comment by achimnol** [comment]
The forked branch push (aka "push to downstream") issue seems more testing and investigation on my side.
Anyway, this PR looks good to me, and I'm merging it.
Sorry for confusion!

**Comment by jangjichang** [comment]
@achimnol  Can you select me as the assigned person?

**Comment by adrysn** [comment]
Assigned!

**Pull request merged**
