### PR TITLE
feat: Allow running images without explicit metadata labels

### LINKED ISSUE #758: Reduce the required information to import a new container image
(initial idea by @hephaex)

To streamline support for arbitrary Docker/container images, let's reduce the required information to import a container image to Backend.AI.

Currently, there are three ways to import a container image:
1. Manually write a Dockerfile to add required `ai.backend.*` labels and copy service-definition files.
   ([Refer the specification](https://docs.backend.ai/en/latest/dev/adding-kernels.html))
2. Use [the image import API in the manager](https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/api/image.py)
3. Use the Forklift service

In all cases, users need to provide [many label options](https://docs.backend.ai/en/latest/dev/adding-kernels.html#metadata-labels).

Since 2019, almost all our customers are relying on the service ports (aka container applications) and startup commands of the batch-type sessions, rather than the REPL-based code execution (usually used by `backend.ai run ...` CLI commands).

So, let's simplify the kernel label specification.

Suggestions:
* Introduce `ai.backend.kernelspec` version 2.
  - Remove all `ai.backend.resource.*`.
  - Remove `ai.backend.runtime-type` by introducing the unified kernel runner which only supports running service ports and the startup script of batch-type sessions.
  - Remove `ai.backend.features` and assume `uid-match` by default.
  - Replace `ai.backend.base-distro` with `ai.backend.base-platform` which follows [the Python's wheel platform tag specification](https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/) such as "manylinux". (See also: [PEP-600](https://peps.python.org/pep-0600/))
    - This could be automatically discovered from the contents of the imported image.
  - Replace `ai.backend.runtime-path` with `ai.backend.python.base` to specify the base path of the image-provided Python runtime.
    - Let's specify only the `sys.prefix` (e.g., `/usr/local`) instead of the full path to the Python executable (e.g., `/usr/local/bin/python`)
    - We may add `ai.backend.{other-language}.base` in the same fashion in the future, which may coexist with the base paths of multiple language runtimes in a single image.
  - Preserve `ai.backend.accelerators`, `ai.backend.service-ports` as-is.
* Assume a default `policy.yml` and avoid requiring copying it for all images.
* Service definitions remain same.
* Automate population of the image-provided bootstrap script
  - NOTE: This may not be possible for "any arbitrary" image, but at least we could try full automation for NGC-based images.
  - Let's _reuse_ the image-provided entrypoint and/or command by passing it to our `entrypoint.sh`.
  - We need to determine whether to run it in the background or foreground.  Maybe we could detect it by whether the image has exposed port numbers or not.
* Make the batch-type session default in `backend.ai run` and avoid reusing existing sessions, which is a legacy from CodeOnWeb.  Guide the users to use `backend.ai start` and `backend.ai ssh` for such REPL use cases.

### LINKED ISSUE #1684: Auto-detect the base-distro (aka glibc version) of container images
Currently we rely on `ai.backend.base-distro` label to choose the appropriate build of statically built in-container applications injected by the agent, such as ttyd and dropbear.

Sometimes, there are human errors to misconfigure this lable or omit it, causing unexpected app launch failures after creating session containers.

Could we read the container image (without lauching it?) to determine the glibc version inside it to automate this process?

### PR DESCRIPTION
**Pull request by kyujin-cho**
This PR:
- resolves #758
- resolves #1684

Let's allow running images without Backend.AI-specific labels, particularly the distro labels to mount compatible kernel-runner binaries.

## Approach 1: Statically built kernel-runner binaries

To ease the burden of managing many per-distro per-version kernel-runner binaries, this PR replaces existing kernel-runner binaries with fully statically built versions, using latest Alpine Linux (3.20).

When we install both `zlib-dev` and `zlib-static` in Alpine Linux, we can statically link zlib. `libressl-dev` already contains the static version `/usr/lib/{libcrypto,libssl,libtls}.a`.

| Component | Version |
|---|---|
| Dropbear | 2020.81 → 2024.85 |
| OpenSSH portable (SFTP and SCP)<br>OpenSSL<br>LibreSSL | 8.1p1 → 9.8p1<br>1.1.1i (removed)<br>3.8.4 (new) |
| tmux | 3.0a → 3.4 |

### Backporting statically built binaries

This PR will not be backported to older releases. Instead, #2625 will target 24.03 and 23.09 releases to partially backport the static builds of the kernel-runner binaries.

## Approach 2: Allowing use of container images without Backend.AI-specific metadata labels

This PR adds a new abstract `Agent` interface: `resolve_image_distro()` to determine the distro-version combination to select the kernel-runner binaries to mount.
Statically building most intrinsic executables makes our life easier, but still `libbaihook.so` and the syscall jail requires to be built against specific libc versions.

`DockerAgent` implements this method by executing `ldd --version` command in a temporary container to get the exact libc (glibc or musl) versions, mapping the libc version to a distro version, and caching this result in Redis for faster resolution at the next time. The cache key is the image ID (digest).

`DummyAgent` falls back to "ubuntu16.04" always.

`KuebernetesAgent` first tries to read the `ai.backend.base-distro` label and raises NotImplementedError if it does not exist.

When scanning an image that does not have metadata labels, the intrinsic slots (`cpu` and `mem`) are filled with `manager.defs.INTRINSIC_SLOTS_MIN` (1 core + 1 GiB). All other min values are assumed to be zero and max values to be infinity. The supported accelerator list is initialized as "*" where frontend implementations should allow setting arbitrary resource slots present in the target resource group.

### CODE REVIEW

**Comment by achimnol** [comment]
Confirmed working of the new tmux, dropbear, and scp binaries.

**Comment by achimnol** [comment]
I've changed the default value of `ai.backend.runtime-path` from "/opt/backend.ai/bin/python" to "/usr/bin/python" because the `/opt/backend.ai` is reserved for the kernel-runner package only, not intended to host user-submitted codes.

**Review by achimnol — CHANGES_REQUESTED** [review]
* Let's invalidate the cache when the image digest is updated upon rescanning container registries.
* Could we use a separate Redis database for this kind of caching data instead of sharing the "stat" database?

**Comment by kyujin-cho** [comment]
> * Let's invalidate the cache when the image digest is updated upon rescanning container registries.
I don't quite get the first point - image digest (what we usually call as image hash) is identical to each atomic image and thus cannot be shared by multiple image even if newer image has been pushed with same image canonical. Is it really necessary to add the invalidation logic?

**Comment by achimnol** [comment]
> > Let's invalidate the cache when the image digest is updated upon rescanning container registries.
> 
> @achimnol I don't quite get the first point - image digest (what we usually call as image hash) is identical to each atomic image and thus cannot be shared by multiple image even if newer image has been pushed with same image canonical. Is it really necessary to add the invalidation logic?

We may rebuild images. Usually, their base-distro are not changed, but for images like `:latest`, it may change. In a long time ago, we decided to **relax** _the tag formatting rule_.

The problem is that if we just allow arbitrary images that does not have any metadata labels nor our specific tag rule, when combined with #411, there will be random container images pulled in the agents. (e.g., `redis:7.2-alpine`, `postgres:16-alpine`, ... on a local all-in-one setup) Currently we are just ignoring "malformed" image tags like `:latest` during rescan since #293.

We also need to check #758 on the default values of the label fields.

**Comment by achimnol** [comment]
* **#2582** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/2582?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kyujin-cho and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by achimnol — APPROVED** [review]

**Pull request merged**
