### PR TITLE
Supplementary explanation to documentation about installation

### PR DESCRIPTION
**Pull request by snaag**
Hello, I am the participant of Hacktoberfest yesterday.
I installed follow to the document, but some contents were not included in the document, so I added it.

### CODE REVIEW

**Review by kyujin-cho — CHANGES_REQUESTED** [review]
Can you add reference to new `install-rustup.md` document on other relevant documents?

**Comment by snaag** [comment]
@kyujin-cho Yes, I added!

**Comment by kyujin-cho** [comment]
Really sorry for the confusion. `_archive` folder is for documents archived and no longer maintained. All updates and new writings should be created under `install` directory directly, with written under reStructuredText syntax. Could you update you PR to do so?

**Comment by snaag** [comment]
I understand. I reset previous commits and push new commit for add documents.

**Comment by achimnol** [comment]
Removed all `_archive` and supplementary installation guide docs in recent update (#872).
This PR is no longer valid, sorry.

**Pull request closed without merging**
