### PR TITLE
feat: Generate INSTALL-INFO after backend.ai install using script (#290)

### PR DESCRIPTION
**Pull request by mindgitrwx**
**Issue:** https://github.com/lablup/backend.ai/issues/290

This PR adds Install_info generate logic in install-dev.sh

When users run ./install-dev.sh, It generates a basic documentation markdown file that has critical information to use backend.ai

image

(I tested this on ubuntu 18,04. I didn't test on other platforms.)

### CODE REVIEW

**Review by achimnol — COMMENTED** [review]
Q. Does it preserve the original terminal output (with colors)?
Q. Does the generated result actually conform with the Markdown syntax?

**Comment by mindgitrwx** [comment]
What I tested so far is here.

Answer 

Q1: I tested this code on ubuntu 18.04 bash, zsh, Macbook terminal, eshell etc. And it preserve the original terminal output. If the colors don't come out as expected, the problem is not with the code, but with the nature of the terminal.

Q2: I think this code is not perfectly conform with the markdown syntax. This picture shows how output comes out. I just simply redirect the code the markdown to reduce complexity of the code.

스크린샷 2021-11-12 오후 5 38 19

**Comment by achimnol** [comment]
I think this should be reworked to provide either Markdown-compliant output or just a plain-text dump.

**Review by achimnol — CHANGES_REQUESTED** [review]
I think this should be reworked to provide either Markdown-compliant output or just a plain text dump.

**Comment by achimnol** [comment]
Closing this as lack of interest and now we rely on Pants for both first-party and 3rd-party dependency mgmt.

**Pull request closed without merging**
