### PR TITLE
feat: Add `kernels.status_history` JSONB column for tracking status transition timestamp

### PR DESCRIPTION
**Pull request by rapsealk**
This PR resolves lablup/backend.ai#412.

It this PR, `status_history` column, which stores JSONB data, is added to `kernels` table. When manager notifies status change on kernels/sessions and tries to update their `status`, they also try to update `status_history` from now on, so that they can track the timestamp of status transition.

### CODE REVIEW

**Comment by rapsealk** [comment]
Now it stores timestamp for each status transition as below:
1. `>> ./backend.ai run --rm python ./main.py`
```json
{
    "kernel": {
        "PENDING": "2022-06-17T04:04:48.104960+00:00",
        "PULLING": "2022-06-17T04:04:48.949588+00:00",
        "RUNNING": "2022-06-17T04:04:52.618655+00:00",
        "PREPARING": "2022-06-17T04:04:49.325617+00:00",
        "SCHEDULED": "2022-06-17T04:04:48.834314+00:00",
        "TERMINATED": "2022-06-17T04:05:15.218716+00:00",
        "TERMINATING": "2022-06-17T04:05:14.561698+00:00"
    },
    "session": {
        "PENDING": "2022-06-17T04:04:48.104960+00:00",
        "PREPARING": "2022-06-17T04:04:48.855234+00:00",
        "TERMINATED": "2022-06-17T04:05:15.263403+00:00"
    }
}
```

2. `>> ./backend.ai session restart`
```json
{
    "kernel": {
        "PULLING": "2022-06-17T01:41:40.979367+00:00",
        "RUNNING": "2022-06-17T01:41:44.168373+00:00",
        "PREPARING": "2022-06-17T01:41:22.332763+00:00",
        "SCHEDULED": "2022-06-17T01:41:21.850976+00:00",
        "RESTARTING": "2022-06-17T01:41:30.626858+00:00",
        "TERMINATED": "2022-06-17T01:45:49.746267+00:00"
    },
    "session": {
        "PENDING": "2022-06-17T01:41:21.144421+00:00",
        "PREPARING": "2022-06-17T01:41:21.869631+00:00",
        "TERMINATED": "2022-06-17T01:45:49.796956+00:00"
    }
}
```

3. `>> ./backend.ai run python ./main.py && ./backend.ai session kill --force`
// created_at: 2022-06-17 11:51:03.479 +0900
// terminated_at: 2022-06-17 11:51:11.463 +0900
```json
{
    "kernel": {
        "PENDING": "2022-06-17T02:51:03.456140+00:00",
        "CANCELLED": "2022-06-17T02:51:11.463812+00:00"
    },
    "session": {
        "PENDING": "2022-06-17T02:51:03.456140+00:00"
    }
}
```

**Comment by rapsealk** [comment]
UPDATE: Now it stores as below:
```json
{
    "PENDING": "2022-06-17T08:53:23.727112+00:00",
    "PULLING": "2022-06-17T08:53:24.665701+00:00",
    "RUNNING": "2022-06-17T08:53:28.468820+00:00",
    "PREPARING": "2022-06-17T08:53:25.091152+00:00",
    "SCHEDULED": "2022-06-17T08:53:24.511698+00:00",
    "TERMINATED": "2022-06-17T08:53:30.917437+00:00",
    "TERMINATING": "2022-06-17T08:53:30.217984+00:00"
}
```

**Review by achimnol — CHANGES_REQUESTED** [review]
As @fregataa has noted, it should include the alembic migration script.

Q. Why did you change `sql_json_merge()` implementation? How about just setting the database-side default value to an empty JSON object?

**Comment by rapsealk** [comment]
@achimnol Thanks for the comment! I changed `sql_json_merge()` to support request like:
```py
sa.update(kernels).values(..., status_history=sql_json_merge(
    kernels.c.status_history, [], {"<new-status>": "<timestamp>"},
))
```

1. If there is no given key, it raises an `IndexError`.
2. While it limits the shape of value to JSON, I thought we need to support for `VARCHAR` string as value to store value in "string:string" format as below:
```json
{
    "PENDING": "2022-06-23T12:30:00.000",
    "PREPARING": "2022-06-23T12:30:10.000",
    ...
    "TERMINATED": "2022-06-23T12:30:20.000"
}
```

**Review by achimnol — APPROVED** [review]

**Pull request merged**
