### PR TITLE
chore: update redis-py requirement from ~= 4.3.4 to ~=4.5.5

### PR DESCRIPTION
**Pull request by Yaminyam**
resolve https://cwe.mitre.org/data/definitions/459.html

### CODE REVIEW

**Comment by inureyes** [comment]
@Yaminyam  Why kernel runner is changed together?

**Review by inureyes — CHANGES_REQUESTED** [review]
Why jail is changed together? Please let me know.

**Comment by Yaminyam** [comment]
@inureyes its my mistake.
If I recently created a new branch, the diff of the jail image is detected even though I haven't made any changes.
If this phenomenon disappears, I think the mistake can be prevented. Do you have any idea what the cause might be?

**Comment by Yaminyam** [comment]
I thought it was a problem that could be solved simply by upgrading the version, but it seems that the changes in redis-py affect while upgrading the version.
There is a part where the test fails, so I think it needs to be resolved.

**Comment by kyujin-cho** [comment]
Seems like there's a regression after redis/redis-py#2671 is merged. Delaying merge until the issue is resolved.

**Comment by achimnol** [comment]
https://github.com/redis/redis-py/releases/tag/v4.5.5 is out 18 hours ago.
Let's try this version.

**Comment by achimnol** [comment]
Now it passes the test suite again!

**Pull request merged**
