### PR TITLE
feat: Support batch session timeout

### LINKED ISSUE #2357: User-defined timeout for batch sessions
Let's allow users set a timeout for batch sessions.

This is a follow-up to #2326.

### PR DESCRIPTION
**Pull request by fregataa**
resolves #2357 

### Test CLI command
```sh
# ./backend.ai session create --type batch -c "echo \"hello world\" && sleep 10" --timeout 5 -t test-batch <IMAGE_NAME>
./backend.ai session create --type batch -c "echo \"hello world\" && sleep 10" --timeout 5 -t test-batch python
```

### Result example
Before #3085
The record from sessions table
image

After #3085 
The record from session table
image

**Checklist:** (if applicable)

- [x] Milestone metadata specifying the target backport version
- [x] Mention to the original issue
- [x] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to:
  - Demonstrate the difference of before/after
  - Demonstrate the flow of abstract/conceptual models with a concrete implementation

----
📚 Documentation preview 📚: https://sorna--3066.org.readthedocs.build/en/3066/

----
📚 Documentation preview 📚: https://sorna-ko--3066.org.readthedocs.build/ko/3066/

### CODE REVIEW

**Comment by fregataa** [comment]
* **#3066** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/3066?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fregataa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by agatha197 — CHANGES_REQUESTED** [review]
How can I test? Can you update PR description?

**Review by agatha197 — APPROVED** [review]
LGTM

**Review by agatha197 — APPROVED** [review]
LGTM

**Pull request merged**
