### PR TITLE
docs: Update session-related commands from the official documentation

### LINKED ISSUE #631: Update docs for session command example
스크린샷 2022-08-07 오후 4 36 18

update: before `backend.ai admin sessions` => after `backend.ai admin session list`

---

스크린샷 2022-08-07 오후 4 43 27

update: before `backend.ai download mysess id_container` => after `backend.ai session download mysess id_container`

### PR DESCRIPTION
**Pull request by qkoo0833**
docs: modifying session command example code

1. backend.ai admin sessions => backend.ai admin session list
2. backend.ai download mysess id_container => backend.ai session download mysess id_container

close #631

### CODE REVIEW

**Comment by qkoo0833** [comment]
`docs` `skip:ci` `skip:changelog`

**Comment by rapsealk** [comment]
Nice work!
By the way, I heard that it is announced that all the works should be merged into the [docs/2022-ossca-translation-base](https://github.com/lablup/backend.ai/tree/docs/2022-ossca-translation-base) branch, rather than directly to the **main**.
Could you please make a new PR?

**Comment by qkoo0833** [comment]
Thx for your review!
I have thougt this documentation change is not translation , but commit changing tutorial docs's code example.
So, I made PR to main.
Could you tell me if it is on right track that make a new PR to the [docs/2022-ossca-translation-base](https://github.com/lablup/backend.ai/tree/docs/2022-ossca-translation-base) branch?

**Comment by rapsealk** [comment]
How about [feature/update-document-to-22.06](https://github.com/lablup/backend.ai/tree/feature/update-document-to-22.06)? We are currently working on this branch for updating our documentations. It will be merged into main branch when it is finished.

**Pull request merged**
